<#
.SYNOPSIS
  Enumerate the DriverStore via pnputil, find INFs with multiple installed
  versions, keep the newest, and write:
    - duplicate-drivers.csv         (for human review)
    - delete-old-drivers.ps1        (pnputil /delete-driver lines, all commented)

  ntprint.inf and prnms*.inf are always excluded (built-in print drivers
  that pnputil refuses to remove).
.PARAMETER OutDir
  Output folder (default: current).
#>
[CmdletBinding()]
param(
    [string]$OutDir = (Get-Location).Path
)

. "$PSScriptRoot\_Common.ps1"
Assert-Admin
Assert-Windows10Plus

Write-Section "枚举 DriverStore"

$raw = & pnputil.exe /enum-drivers 2>&1 | Out-String
$blocks = $raw -split "`r?`n`r?`n" | Where-Object { $_ -match 'Published Name|发布名称' }

$entries = foreach ($b in $blocks) {
    $h = @{}
    foreach ($line in ($b -split "`r?`n")) {
        if ($line -match '^\s*([^:]+?)\s*:\s*(.+?)\s*$') {
            $h[$Matches[1].Trim()] = $Matches[2].Trim()
        }
    }
    $published = $h['Published Name'];          if (-not $published) { $published = $h['发布名称'] }
    $original  = $h['Original Name'];           if (-not $original)  { $original  = $h['原始名称'] }
    $provider  = $h['Provider Name'];           if (-not $provider)  { $provider  = $h['提供程序名称'] }
    $class     = $h['Class Name'];              if (-not $class)     { $class     = $h['类名称'] }
    $version   = $h['Driver Version'];          if (-not $version)   { $version   = $h['驱动程序版本'] }
    $date      = $h['Driver Date'];             if (-not $date)      { $date      = $h['驱动程序日期'] }
    if (-not $published) { continue }
    [PSCustomObject]@{
        PublishedName = $published
        OriginalName  = ($original   ? $original.ToLowerInvariant() : '')
        Provider      = $provider
        Class         = $class
        Date          = $date
        Version       = $version
        VersionParsed = (try { [Version]($version -replace '[^\d.]','') } catch { [Version]'0.0' })
    }
}

if (-not $entries) {
    Write-Host "未解析到驱动条目。可能是 pnputil 输出格式变化，请手工运行 pnputil /enum-drivers 检查。" -ForegroundColor Red
    exit 1
}

# Group by inf and keep newest
$groups = $entries | Group-Object OriginalName | Where-Object { $_.Count -gt 1 }
$excludeInf = @('ntprint.inf','prnms001.inf','prnms002.inf','prnms003.inf','prnms009.inf')

$dupRows = foreach ($g in $groups) {
    if ($excludeInf -contains $g.Name) { continue }
    $sorted = $g.Group | Sort-Object VersionParsed -Descending
    $keep   = $sorted[0]
    foreach ($old in $sorted | Select-Object -Skip 1) {
        [PSCustomObject]@{
            INF           = $g.Name
            DeleteOEM     = $old.PublishedName
            DeleteVersion = $old.Version
            DeleteDate    = $old.Date
            KeepOEM       = $keep.PublishedName
            KeepVersion   = $keep.Version
            KeepDate      = $keep.Date
            Provider      = $old.Provider
            Class         = $old.Class
        }
    }
}

if (-not $dupRows) {
    Write-Host "未发现重复驱动。" -ForegroundColor Green
    return
}

$csvPath = Join-Path $OutDir 'duplicate-drivers.csv'
$psPath  = Join-Path $OutDir 'delete-old-drivers.ps1'

$dupRows | Sort-Object INF | Export-Csv -LiteralPath $csvPath -Encoding UTF8 -NoTypeInformation

$lines = @(
    '# Auto-generated by Get-DuplicateDrivers.ps1',
    '# 全部命令默认注释。审核 duplicate-drivers.csv 后，按批次取消注释执行。',
    '# 推荐顺序：1) 显卡  2) 蓝牙  3) 其余',
    '# 每批执行后重启验证对应硬件再做下一批。',
    ''
)
foreach ($r in ($dupRows | Sort-Object INF)) {
    $lines += "# $($r.INF)   keep $($r.KeepVersion) ($($r.KeepOEM))   delete $($r.DeleteVersion) ($($r.DeleteOEM))"
    $lines += "# pnputil /delete-driver $($r.DeleteOEM) /uninstall /force"
    $lines += ''
}
$lines | Set-Content -LiteralPath $psPath -Encoding UTF8

Write-Host ""
Write-Host "生成: $csvPath" -ForegroundColor Green
Write-Host "生成: $psPath  (所有命令默认注释)" -ForegroundColor Green
Write-Host ""
Write-Host "审查 CSV 后，使用 Invoke-Stage6-DriverCleanup.ps1 -Batch 分批启用执行。" -ForegroundColor Yellow
