#!/usr/bin/env python3
"""
Video Processor - 视频剪辑和字幕烧录
FFmpeg封装，处理视频裁剪和字幕烧录
"""

import os
import sys
import shutil
import tempfile
import subprocess
from pathlib import Path
from dataclasses import dataclass


@dataclass
class ProcessResult:
    success: bool
    output_path: str
    message: str


class VideoProcessor:
    def __init__(self, ffmpeg_path: str = "ffmpeg", output_dir: str = "./youtube-clips/output"):
        self.ffmpeg_path = ffmpeg_path
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def clip_video(
        self,
        input_video: str,
        start_time: str,
        end_time: str,
        output_name: str = "clip.mp4"
    ) -> ProcessResult:
        """
        剪辑视频片段

        Args:
            input_video: 输入视频路径
            start_time: 开始时间 (HH:MM:SS)
            end_time: 结束时间 (HH:MM:SS)
            output_name: 输出文件名

        Returns:
            ProcessResult
        """
        output_path = self.output_dir / output_name

        # 计算时长
        duration = self._calculate_duration(start_time, end_time)

        cmd = [
            self.ffmpeg_path,
            "-y",  # 覆盖输出
            "-ss", start_time,
            "-i", input_video,
            "-t", str(duration),
            "-c:v", "libx264",
            "-c:a", "aac",
            "-strict", "experimental",
            str(output_path)
        ]

        return self._run_ffmpeg(cmd, str(output_path))

    def burn_subtitles(
        self,
        input_video: str,
        subtitle_file: str,
        output_name: str = "with_subtitles.mp4",
        style: str = "FontName=Arial,FontSize=24,PrimaryColour=&H00FFFFFF,OutlineColour=&H00000000,Outline=2,Bold=1"
    ) -> ProcessResult:
        """
        烧录字幕到视频

        关键问题: FFmpeg subtitles滤镜无法处理含空格的路径
        解决方案: 使用temp目录处理

        Args:
            input_video: 输入视频路径
            subtitle_file: SRT字幕文件路径
            output_name: 输出文件名
            style: 字幕样式

        Returns:
            ProcessResult
        """
        output_path = self.output_dir / output_name

        # 创建临时目录（处理路径空格问题）
        temp_dir = tempfile.mkdtemp(prefix="yt_clipper_")
        temp_video = shutil.copy(input_video, temp_dir)
        temp_subtitle = shutil.copy(subtitle_file, temp_dir)

        try:
            # 转SRT为ASS（FFmpeg subtitles滤镜直接支持SRT，但ASS更灵活）
            ass_subtitle = self._convert_srt_to_ass(
                temp_subtitle,
                style=style.replace('Bold=1', 'Bold=-1')
            )

            cmd = [
                self.ffmpeg_path,
                "-y",
                "-i", temp_video,
                "-vf", f"ass={ass_subtitle}",
                "-c:a", "copy",
                str(output_path)
            ]

            return self._run_ffmpeg(cmd, str(output_path))

        finally:
            # 清理临时目录
            shutil.rmtree(temp_dir, ignore_errors=True)

    def extract_subtitle_segment(
        self,
        subtitle_file: str,
        start_time: str,
        end_time: str
    ) -> str:
        """
        提取字幕片段

        Args:
            subtitle_file: 原始字幕文件
            start_time: 开始时间
            end_time: 结束时间

        Returns:
            提取的字幕内容
        """
        import pysrt

        try:
            subs = pysrt.open(subtitle_file)
        except Exception:
            # VTT格式转换
            subs = self._convert_vtt_to_srt(subtitle_file)

        # 筛选时间范围内的字幕
        start_seconds = self._time_to_seconds(start_time)
        end_seconds = self._time_to_seconds(end_time)

        filtered = []
        for sub in subs:
            if start_seconds <= sub.start.ordinal // 1000 <= end_seconds:
                # 调整时间戳
                sub.start = sub.start.shift(seconds=-start_seconds)
                sub.end = sub.end.shift(seconds=-start_seconds)
                filtered.append(sub)

        # 保存提取的字幕
        output_path = self.output_dir / "extracted_subtitle.srt"
        pysrt.compose(filtered).save(str(output_path), encoding='utf-8')

        return str(output_path)

    def _convert_srt_to_ass(self, srt_path: str, style: str = "") -> str:
        """SRT转ASS格式（FFmpeg烧录更稳定）"""
        # 简单转换：生成ASS头+字幕
        with open(srt_path, 'r', encoding='utf-8') as f:
            content = f.read()

        ass_header = f"""[Script Info]
Title: Generated by YouTube Clipper
ScriptType: v4.00+

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{style},Alignment=2

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

        # 转换字幕格式
        lines = content.strip().split('\n\n')
        ass_events = []

        for block in lines:
            parts = block.strip().split('\n')
            if len(parts) < 3:
                continue

            time_line = parts[1]
            text = '<br>'.join(parts[2:])

            # 转换时间格式 SRT -> ASS
            time_match = time_line.split('-->')
            if len(time_match) != 2:
                continue

            def convert_time(t):
                t = t.strip().replace(',', '.')
                parts = t.split(':')
                h, m = parts[0], parts[1]
                s, ms = parts[2].split('.')
                return f"{h}:{m}:{s}.{ms}"

            start = convert_time(time_match[0])
            end = convert_time(time_match[1])

            # 清理文本中的标签
            import re
            text = re.sub(r'<[^>]+>', '', text)

            ass_events.append(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{text}")

        ass_content = ass_header + '\n'.join(ass_events)

        # 保存ASS文件
        output_path = srt_path.replace('.srt', '.ass')
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(ass_content)

        return output_path

    def _convert_vtt_to_srt(self, vtt_path: str) -> 'pysrt.SubRipFile':
        """VTT转pysrt对象"""
        import pysrt

        with open(vtt_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # VTT转SRT文本
        srt_content = content
        srt_content = srt_content.replace('WEBVTT\n\n', '')
        srt_content = srt_content.replace('WEBVTT\n', '')
        srt_content = srt_content.replace('.', ',')
        srt_content = srt_content.replace(r'<\d{2}:\d{2}:\d{2}', '')  # 移除cue identifiers

        # 保存为临时SRT
        temp_srt = vtt_path.replace('.vtt', '.srt')
        with open(temp_srt, 'w', encoding='utf-8') as f:
            f.write(srt_content)

        return pysrt.open(temp_srt)

    def _calculate_duration(self, start: str, end: str) -> float:
        """计算时长（秒）"""
        return self._time_to_seconds(end) - self._time_to_seconds(start)

    def _time_to_seconds(self, time_str: str) -> float:
        """时间字符串转秒数"""
        import re
        match = re.match(r'(\d+):(\d+):([\d.]+)', time_str)
        if match:
            h, m, s = match.groups()
            return int(h) * 3600 + int(m) * 60 + float(s)
        return 0

    def _run_ffmpeg(self, cmd: list, output_path: str) -> ProcessResult:
        """执行FFmpeg命令"""
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=300
            )

            if result.returncode == 0:
                return ProcessResult(
                    success=True,
                    output_path=output_path,
                    message="Success"
                )
            else:
                return ProcessResult(
                    success=False,
                    output_path="",
                    message=f"FFmpeg error: {result.stderr[-500:]}"
                )

        except subprocess.TimeoutExpired:
            return ProcessResult(
                success=False,
                output_path="",
                message="FFmpeg timeout (>5 min)"
            )
        except Exception as e:
            return ProcessResult(
                success=False,
                output_path="",
                message=str(e)
            )


def main():
    if len(sys.argv) < 4:
        print("Usage: python video_processor.py <command> <args...>")
        print("Commands:")
        print("  clip <video> <start> <end> [output]")
        print("  burn <video> <subtitle> [output]")
        sys.exit(1)

    cmd = sys.argv[1]
    processor = VideoProcessor()

    if cmd == "clip":
        video = sys.argv[2]
        start = sys.argv[3]
        end = sys.argv[4]
        output = sys.argv[5] if len(sys.argv) > 5 else "clip.mp4"

        result = processor.clip_video(video, start, end, output)
        print(f"Clip: {'✓' if result.success else '✗'} {result.message}")

    elif cmd == "burn":
        video = sys.argv[2]
        subtitle = sys.argv[3]
        output = sys.argv[4] if len(sys.argv) > 4 else "with_subtitles.mp4"

        result = processor.burn_subtitles(video, subtitle, output)
        print(f"Burn: {'✓' if result.success else '✗'} {result.message}")


if __name__ == "__main__":
    main()
