# -*- coding: utf-8 -*-
{
    'name': 'Odoo 19.0 Template',
    'version': '19.0.1.0.0',
    'category': 'Tools',
    'summary': 'Generated by Odoo Specialist Skill',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/templates.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
